### ISSUE TITLE
Hi i run it in console and get this error. please help

### ISSUE THREAD

**Issue by baophamthien241098** [RGB-Outl4w/AutoFarmCatizen#1]
handleError.ts:42 EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' https://t.me/_websync_ https://telegram.me/_websync_".

**Comment by RGB-Outl4w** [comment]
Hello. Can you provide the full command you've ran in console?

**Comment by baophamthien241098** [comment]
> Hello. Can you provide the full command you've ran in console?

fetch('https://raw.githubusercontent.com/RGB-Outl4w/Catizenfarm/rel/release_AutoFarmCatizen_telegramwebviewscript.js').then(response => response.text()).then(script => eval(script)); . here @RGB-Outl4w . Thanks a lot

**Comment by RGB-Outl4w** [comment]
You can try typing `allow pasting` into the console if you haven't done it previously. Then, try using this one: `fetch('https://raw.githubusercontent.com/RGB-Outl4w/AutoFarmCatizen/rel/release_AutoFarmCatizen_telegramwebviewscript.js').then(response => response.text()).then(script => eval(script));`

**Comment by baophamthien241098** [comment]
![Screenshot](https://github.com/RGB-Outl4w/AutoFarmCatizen/assets/43930927/39ed8035-1f74-40b9-bcb5-afa134930f85)
yeap @RGB-Outl4w , but i still get this error

**Comment by RGB-Outl4w** [comment]
Could you try again? I've made a small change to the script. It worked for me before and still works now, your case is quite unusual.

And if this doesn't help after allowing pasting, then I guess I'll have to dive deeper into this problem. Tested it on 3 different accounts, no errors on execution.

Command: `fetch('https://raw.githubusercontent.com/RGB-Outl4w/AutoFarmCatizen/rel/release_AutoFarmCatizen_telegramwebviewscript.js').then(response => response.text()).then(script => eval(script));`

**Comment by sak1ch** [comment]
Where to send the code:
fetch('https://raw.githubusercontent.com/RGB-Outl4w/AutoFarmCatizen/rel/release_AutoFarmCatizen_telegramwebviewscript.js').then(response => response.text()).then(script => eval(script));
Do I need to run the catizen web application before inserting this command, and do I need to download all the files that you have attached?

**Comment by RGB-Outl4w** [comment]
@sak1ch, hello there. First, open up the Catizen web app on your PC. Then, while having it open, press **[Ctrl + Shift + i]** on your keyboard. This should open up a console. There you should type `allow pasting` if you've never used the console before. Then, insert the script into the console and press **[Enter]**. This should do the job if everything's done correctly.

**To get access to the console, you first have to**: Go to Settings -> Advanced -> Experimental settings -> Enable webview inspection.

**Comment by baophamthien241098** [comment]
I think problem is not about script. Somehow the eval() can not run text. @RGB-Outl4, you ran the same command and it work ?

**Comment by RGB-Outl4w** [comment]
@baophamthien241098, Yes, that's the thing. It works flawlessly for me, so I genuinely have no clue why it doesn't for you.

**Comment by baophamthien241098** [comment]
Which browser did you use ? Chrome 🤔 @RGB-Outl4w

**Comment by Widiskel** [comment]
still not solved

**Comment by Widiskel** [comment]
here the error message
"Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' https://t.me/_websync_ https://telegram.me/_websync_".
"

**Comment by RGB-Outl4w** [comment]
> Which browser did you use ? Chrome 🤔 @RGB-Outl4w 

Browser for what exactly? I use a web app launched in Telegram Desktop

**Comment by Widiskel** [comment]
> > Which browser did you use ? Chrome 🤔 @RGB-Outl4w
> 
> Browser for what exactly? I use a web app launched in Telegram Desktop

ahh, i think that the problem , gonna try telegram desktop

**Comment by KayNguyen97** [comment]
After open inspect web by Ctrl + Shift + i . Where will I fill in the order?

**Comment by RGB-Outl4w** [comment]
> After open inspect web by Ctrl + Shift + i . Where will I fill in the order?

@KayNguyen97 You should see multiple tabs at the top of the window. Like those:
![image](https://github.com/RGB-Outl4w/AutoFarmCatizen/assets/101356538/1713975e-ad8f-4165-a4e3-62577b0e483c)

Here you need to select "Console". A "command prompt" will be opened. Paste the script command there and press Enter.

If it's your first time opening console, you need to type 'allow pasting' there first.

**Comment by KayNguyen97** [comment]
How to open console by telegram desktop

**Comment by RGB-Outl4w** [comment]
> How to open console by telegram desktop

Here, made a step-by-step guide on how to do it: https://telegra.ph/How-to-open-webview-inspecting-window-console-03-23
