### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by arifintajul4** [RGB-Outl4w/AutoFarmCatizen#10]
please add fitur to click this boost
<img width="333" alt="Screenshot 2024-04-22 at 18 17 12" src="https://github.com/RGB-Outl4w/AutoFarmCatizen/assets/36062540/2ff86a4b-4fa3-48e4-b580-967e1b00012f">

**Comment by RGB-Outl4w** [comment]
> please add fitur to click this boost

Thank you for the idea, I'll do my best to do some research on this topic ant try to find stuff related to it. If you already have valuable information on this topic, don't be afraid to share it, and it will pay you off!

**Comment by RGB-Outl4w** [comment]
@arifintajul4, alright, so, based on my research, the main function of "Auto" button does include auto-collecting of such bonuses, so there is no need to change anything. Though it only uses the "Free" version of this boost, it still auto-collects it.
