### ISSUE TITLE
Catizen Update

### ISSUE THREAD

**Issue by burnmine** [RGB-Outl4w/AutoFarmCatizen#11]
Catizen has been updated, and this script no longer works. Are there any updates to this script?

**Comment by RGB-Outl4w** [comment]
> Catizen has been updated, and this script no longer works. Are there any updates to this script?

Hello, there are currently no updates for the script. I'm still working on it, hold tight.

**Comment by burnmine** [comment]
ok thanks rgb

**Comment by burnmine** [comment]
> > Catizen has been updated, and this script no longer works. Are there any updates to this script?
> 
> Hello, there are currently no updates for the script. I'm still working on it, hold tight.

Ok thanks RGB

**Comment by youngbloodes** [comment]
How's it going, mr RGB

**Comment by RGB-Outl4w** [comment]
> How's it going, mr RGB

So far so... unsuccessful, sadly. No updates yet.

**Comment by youngbloodes** [comment]
Okayy, btw, thanks

**Comment by RGB-Outl4w** [comment]
The code has been updated, check OAFC v5.1.
