### ISSUE TITLE
Both methods are fixed :(

### ISSUE THREAD

**Issue by 66th-soul** [RGB-Outl4w/AutoFarmCatizen#13]
Alternative version (OAFC v5.0) now not working :(

**Comment by RGB-Outl4w** [comment]
> Alternative version (OAFC v5.0) now not working :(

Sadly, yes. I have already addressed this problem and currently no solutions are available. Stay tuned!

**Comment by thuydao** [comment]
can you public your code, deobfuscate your code, i will try to help you

**Comment by nthanhtung92** [comment]
> can you public your code, deobfuscate your code, i will try to help you

code public sẵn rồi bác, bác đọc readme ý

**Comment by RGB-Outl4w** [comment]
Code has been updated, check OAFC v5.1.

**Comment by thuydao** [comment]
Thanks bro
