### ISSUE TITLE
Can you help

### ISSUE THREAD

**Issue by sea2016new** [RGB-Outl4w/AutoFarmCatizen#3]
Can you help optimize this script to automatically buy a cat when there is enough currency?

**Comment by sea2016new** [comment]
If I run the game in the web version of Telegram and then input your script into the web console, but encounter errors, can the script be made compatible with the web platform?
error:

fetch('https://raw.githubusercontent.com/RGB-Outl4w/AutoFarmCatizen/rel/release_AutoFarmCatizen_telegramwebviewscript.js').then(response => response.text()).then(script => eval(script));
Promise {<pending>}
VM214:1  Uncaught (in promise) ReferenceError: Laya is not defined
    at mainLoop (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (:2:173))), <anonymous>:1:4707)
    at eval (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (:2:173))), <anonymous>:1:6392)
    at eval (eval at <anonymous> (eval at <anonymous> (:2:173)), <anonymous>:1:1)
    at eval (eval at <anonymous> (:2:173), <anonymous>:2:20457)
    at <anonymous>:2:173

**Comment by whatever193** [comment]
Scrip only work with telegram desktop app, web browser will not working

**Comment by sea2016new** [comment]
Certainly, there is another question: Can you help optimize this script to automatically buy a cat when there is enough currency?

**Comment by whatever193** [comment]
I find that unnecessary, you just need to hang it for 12 hours and buy it once

**Comment by sea2016new** [comment]
Okay, thank you very much.

**Comment by RGB-Outl4w** [comment]
@sea2016new, hello. Recently I've released the OAFC v5.0 file which includes automated purchasing of the currently relevant cat. Try it out!

P.S. Be sure to check [README.md](https://github.com/RGB-Outl4w/AutoFarmCatizen/blob/rel/README.md) for more info about the release.
