### ISSUE TITLE
hello, can u give the source without decode, i want to learn about automation, thank you very much

### ISSUE THREAD

**Issue by dinhvanhieu3011** [RGB-Outl4w/AutoFarmCatizen#5]

**Comment by RGB-Outl4w** [comment]
Hello! Sad it may seem, but I'm not doing any source giveaways on this project right now. You can still find all three scripts in their pure unobfuscated form on my [boosty](https://boosty.to/rgboutlaw).

**Comment by dinhvanhieu3011** [comment]
You mean, i can buy it on your boosty. Oh, thank you, i will buy it for my learn
