### ISSUE TITLE
autobuying doesn't work

### ISSUE THREAD

**Issue by ExternusKey** [RGB-Outl4w/AutoFarmCatizen#6]
I dunno why, but autobuying doesn't work for me? Can you help or do somethin?

**Comment by ExternusKey** [comment]
Merge and opening working fine, but buing - no

**Comment by RGB-Outl4w** [comment]
Hello, @ExternusKey . I'm afraid that the auto buying function is simply not the one that you expected it to be. It doesn't buy cats non-stop, but only once in some time. Call it intervals. For example, it buys a cat once in 10 minutes. I didn't count, so I don't know the real interval time. But that's just how it works.
