### ISSUE TITLE
why obfuscated code

### ISSUE THREAD

**Issue by rntdev1** [RGB-Outl4w/AutoFarmCatizen#7]
Why did you obfuscate all code? How do I decode??? How can I guarantee that it won't send my token to you?

**Comment by RGB-Outl4w** [comment]
Hello. Firstly, the script is not intended to be deobfuscated for the sake of security and originality of the project. Secondly, to answer your question, your guarantors of security are the amount of stars and forks on this repo.

Let me say that I wouldn't put stars and fork repositories if I were to realize that the scripts contain malicious code after executing them.

And lastly, **there is no actual way to access the source code as long as you don't have access to the boosty page**.

I hope I've answered your question.

**Comment by eastsida** [comment]
Code doesn't work anymore

**Comment by RGB-Outl4w** [comment]
> Code doesn't work anymore

Hello. While I'm aware of the main script now being kind of broken and that stops it from working, there is still OAFC 5.0 available, which works pretty well.

**Comment by RGB-Outl4w** [comment]
> > > Code doesn't work anymore
> > 
> > 
> > Hello. While I'm aware of the main script now being kind of broken and that stops it from working, there is still OAFC 5.0 available, which works pretty well.
> 
> I am pasting OAFC 5.0 and nothing happens. How yours works ? )

You gotta wait for ~3 seconds for it to load properly and then press the "Auto" in-game button

**Comment by RGB-Outl4w** [comment]
Comments have gone off-topic, main question answered
